###
POST http://127.0.0.1:8000/wireguard/servers/
Content-Type: application/json

{
  "name": "iran-main-server",
  "interface_name": "wg0",
  "address_cidr": "10.10.0.1/24",
  "listen_port": 51820,
  "public_endpoint": "vpn.example.com",
  "dns": "1.1.1.1",
  "allowed_ips": "10.10.0.0/24"
}

### Create WireGuard client without auth
POST http://localhost:8000/wireguard/servers/1/clients/
Content-Type: application/json

{
  "name": "client-01",
  "dns": "1.1.1.1",
  "description": "First client for testing"
}

### Get WireGuard client config without auth
GET http://localhost:8000/wireguard/clients/1/config/
Accept: application/json

### Get WireGuard client config without auth
GET http://localhost:8000/wireguard/clients/1/config/download/

###
GET http://localhost:8000/wireguard/servers/
Content-Type: application/json