# Generated by Django 6.0.6 on 2026-10-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interface_name', models.CharField(default='wg0', max_length=20)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('address_cidr', models.CharField(max_length=50)),
                ('listen_port', models.PositiveIntegerField(default=51820)),
                ('public_endpoint', models.CharField(max_length=255)),
                ('dns', models.CharField(blank=True, default='1.1.1.1', max_length=255)),
                ('allowed_ips', models.CharField(default='10.10.0.0/24', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WireGuardClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('preshared_key', models.TextField(blank=True, default='')),
                ('address', models.CharField(max_length=50)),
                ('dns', models.CharField(blank=True, default='1.1.1.1', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='wirequardApp.wireguardserver')),
            ],
            options={
                'unique_together': {('server', 'name')},
            },
        ),
    ]
